/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UAS;

import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Scanner;
import java.util.Date;
/**
 *
 * @author LENOVO
 */
public class GBarang extends javax.swing.JFrame {
    DefaultTableModel tabel;
    /**
     * Creates new form GBarang
     */
    public GBarang() {
        initComponents();
        initTable();
    }
    public void initTable () {
        String [] judul = {"ID Barang","Kode Barang", "Nama Barang", "Jenis Barang", "Harga", "Stok", "TanggalMasuk"};
        tabel = new DefaultTableModel(judul,0);
        tabelBarang.setModel(tabel);
        tampilkanData();
        SettOff();
    }
    private void tampilkanData(){
        int row = tabel.getRowCount();
        for (int a=0; a<row; a++){
        tabel.removeRow(0);
        }
        try{
            Connection cn = (Connection)Conn.koneksiDB();
            ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM gbarang");
            while (rs.next()){
                String data[] ={
                    rs.getString("IDBarang"),
                    rs.getString("KodeBarang"),
                    rs.getString("NamaBarang"),
                    rs.getString("Jenis"),
                    rs.getString("Harga"),
                    rs.getString("Stok"),
                    rs.getString("TanggalMasuk") 
                };
                tabel.addRow(data);
            } 
        }catch (SQLException ex){
        Logger.getLogger(GBarang.class.getName()).log(Level.SEVERE, null, ex);
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GBarang.class.getName()).log(Level.SEVERE, null, ex);
        }

        tSimpan.setEnabled(false);
        tEdit.setEnabled(false);
        tHapus.setEnabled(false);
        tKembali.setEnabled(false);
        tKeluar.setEnabled(true);
    }
    
      private void Clear(){
        inputID.setText("");
        inputKode.setText("");
        inputNama.setText("");
        inputJenis2.setSelectedIndex(0);
        inputHarga.setText("");
        inputStok.setText("");
        }
      private void SettOff(){
        inputID.setEnabled(false);
        inputKode.setEnabled(false);
        inputNama.setEnabled(false);
        inputJenis2.setEnabled(false);
        inputHarga.setEnabled(false);
        inputStok.setEnabled(false);
        }
      private void SettOn(){
        inputKode.setEnabled(true);
        inputNama.setEnabled(true);
        inputJenis2.setEnabled(true);
        inputHarga.setEnabled(true);
        inputStok.setEnabled(true);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jKBarang = new javax.swing.JLabel();
        inputKode = new javax.swing.JTextField();
        jNBarang = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        jJBarang = new javax.swing.JLabel();
        jHSatuan = new javax.swing.JLabel();
        inputHarga = new javax.swing.JTextField();
        jSGudang = new javax.swing.JLabel();
        inputStok = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tTambah = new javax.swing.JButton();
        tSimpan = new javax.swing.JButton();
        tEdit = new javax.swing.JButton();
        tHapus = new javax.swing.JButton();
        tKeluar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        tKembali = new javax.swing.JButton();
        jKBarang1 = new javax.swing.JLabel();
        inputID = new javax.swing.JTextField();
        inputJenis2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jKBarang.setText("Kode Barang");

        jNBarang.setText("Nama Barang");

        jJBarang.setText("Jenis Barang");

        jHSatuan.setText("Harga Satuan");

        jSGudang.setText("Stok Gudang");

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("Gudang Barang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        tTambah.setBackground(new java.awt.Color(40, 167, 69));
        tTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tTambah.setForeground(new java.awt.Color(255, 255, 255));
        tTambah.setText("Tambah");
        tTambah.setPreferredSize(new java.awt.Dimension(114, 28));
        tTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTambahActionPerformed(evt);
            }
        });

        tSimpan.setBackground(new java.awt.Color(0, 123, 255));
        tSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tSimpan.setForeground(new java.awt.Color(255, 255, 255));
        tSimpan.setText("Simpan");
        tSimpan.setPreferredSize(new java.awt.Dimension(72, 28));
        tSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSimpanActionPerformed(evt);
            }
        });

        tEdit.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        tEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tEdit.setForeground(new java.awt.Color(255, 255, 255));
        tEdit.setText("Edit");
        tEdit.setPreferredSize(new java.awt.Dimension(72, 28));
        tEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEditActionPerformed(evt);
            }
        });

        tHapus.setBackground(new java.awt.Color(220, 53, 69));
        tHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tHapus.setForeground(new java.awt.Color(255, 255, 255));
        tHapus.setText("Hapus");
        tHapus.setPreferredSize(new java.awt.Dimension(72, 28));
        tHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tHapusActionPerformed(evt);
            }
        });

        tKeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tKeluar.setText("Keluar");
        tKeluar.setPreferredSize(new java.awt.Dimension(72, 28));
        tKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKeluarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("Tabel Barang");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tabelBarang.setBackground(new java.awt.Color(204, 204, 204));
        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Barang", "Kode Barang", "Nama Barang", "Jenis Barang", "Harga ", "Stok Gudang", "Tanggal Masuk"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBarang);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel3.setText("Form Input Barang");

        tKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tKembali.setText("Kembali");
        tKembali.setPreferredSize(new java.awt.Dimension(74, 28));
        tKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKembaliActionPerformed(evt);
            }
        });

        jKBarang1.setText("ID Barang");

        inputJenis2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baju", "Celana", "Jaket", "Kemeja", "Kaos" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jHSatuan)
                                        .addGap(279, 279, 279))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSGudang)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(tHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(tSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(tKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jKBarang)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                    .addComponent(inputKode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jNBarang)
                                        .addComponent(jJBarang)
                                        .addComponent(jKBarang1))
                                    .addGap(24, 24, 24)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(inputID, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(inputNama, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(inputHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(inputStok, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(inputJenis2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(jLabel3)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jKBarang1))
                    .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jKBarang)
                            .addComponent(inputKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jNBarang)
                            .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jJBarang)
                            .addComponent(inputJenis2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jHSatuan)
                            .addComponent(inputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSGudang)
                            .addComponent(inputStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTambahActionPerformed
        Clear();
        inputKode.requestFocus();
        inputID.setEnabled(false);
        tSimpan.setEnabled(true);
        tEdit.setEnabled(false);
        tHapus.setEnabled(false);
        SettOn();
    }//GEN-LAST:event_tTambahActionPerformed

    private void tabelBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBarangMouseClicked
        // TODO add your handling code here:
        
        try {
            Connection cn = (Connection)Conn.koneksiDB();
            int row =tabelBarang.getSelectedRow();
            inputID.setText(tabelBarang.getValueAt(row, 0).toString());
            inputKode.setText(tabelBarang.getValueAt(row, 1).toString());
            inputNama.setText(tabelBarang.getValueAt(row, 2).toString());
            inputJenis2.setSelectedItem(tabelBarang.getValueAt(row, 3).toString());
            inputHarga.setText(tabelBarang.getValueAt(row, 4).toString());
            inputStok.setText(tabelBarang.getValueAt(row, 5).toString());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Data Gagal Diubah...");

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
        SettOn();
        inputID.setEnabled(false);
        tSimpan.setEnabled(true);
        tEdit.setEnabled(true);
        tHapus.setEnabled(true);
        tKeluar.setEnabled(true);
        tKembali.setEnabled(true);
    }//GEN-LAST:event_tabelBarangMouseClicked

    private void tEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEditActionPerformed
        String IDBarang =inputID.getText();
        String KodeBarang =inputKode.getText();
        String NamaBarang =inputNama.getText();
        String Jenis =inputJenis2.getSelectedItem().toString();
        String Harga =inputHarga.getText();
        String Stok =inputStok.getText();

        java.util.Date tanggal = new java.util.Date();
        java.text.SimpleDateFormat TanggalFormat= new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String TanggalMasuk=TanggalFormat.format(tanggal);
        
        if (KodeBarang.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"Kode produk tidak boleh kosong");
            inputKode.requestFocus();
        }else if (NamaBarang.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Nama produk tidak boleh kosong");
            inputNama.requestFocus();
        }else if (Jenis.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Jenis produk tidak boleh kosong");
            inputJenis2.requestFocus();
        }else if (Harga.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Harga produk tidak boleh kosong");
            inputHarga.requestFocus();
        }else if (Stok.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Stok produk tidak boleh kosong");
            inputStok.requestFocus();
        }
        else if (!(new Scanner(Harga).hasNextInt())) {
            JOptionPane.showMessageDialog(null,"Harga produk harus angka");
            inputHarga.requestFocus();
        }else if (!(new Scanner(Stok).hasNextInt())) {
            JOptionPane.showMessageDialog(null,"Stok produk harus angka");
            inputStok.requestFocus();
        }else{
        try {
            // TODO add your handling code here:
            Connection cn = (Connection)Conn.koneksiDB();
            Statement stt=cn.createStatement();
            stt.executeUpdate("UPDATE gbarang SET KodeBarang='"+KodeBarang+"',NamaBarang='"+NamaBarang+"', Jenis='"+Jenis+"', Harga='"+Harga+"',"+
                "Stok='"+Stok+"' WHERE IDBarang='"+IDBarang+"'");
            tampilkanData();
            JOptionPane.showMessageDialog(null, "Update Berhasil");
            Clear();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Data Gagal Diubah...");
        }   catch (ClassNotFoundException ex) {
                Logger.getLogger(GBarang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tEditActionPerformed

    private void tHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tHapusActionPerformed
        // TODO add your handling code here:
        String KodeBarang=inputKode.getText();

        if (KodeBarang.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"Kode produk tidak boleh kosong");
            inputKode.requestFocus();
        } else if(JOptionPane.showConfirmDialog(null,"Apakah anda yakin akan menghapus data ini?",
            "Informasi",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE)==JOptionPane.OK_OPTION){
        try{
            Connection cn = (Connection)Conn.koneksiDB();
            Statement stt=cn.createStatement();
            stt.executeUpdate("DELETE FROM gbarang WHERE KodeBarang='"+KodeBarang+"'");
            Clear();
        tampilkanData();
            JOptionPane.showMessageDialog(this,"Data berhasil di hapus","Success",JOptionPane.INFORMATION_MESSAGE);
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this,"Delete data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }   catch (ClassNotFoundException ex) {
                Logger.getLogger(GBarang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tHapusActionPerformed

    private void tKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_tKeluarActionPerformed

    private void tSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSimpanActionPerformed
        // TODO add your handling code here:
        String KodeBarang =inputKode.getText();
        String NamaBarang =inputNama.getText();
        String Jenis =inputJenis2.getSelectedItem().toString();
        String Harga =inputHarga.getText();
        String Stok =inputStok.getText();

        java.util.Date tanggal = new java.util.Date();
        java.text.SimpleDateFormat TanggalFormat= new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String TanggalMasuk = TanggalFormat.format(tanggal);

        if (KodeBarang.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"Kode produk tidak boleh kosong");
            inputKode.requestFocus();
        } else if (NamaBarang.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Nama produk tidak boleh kosong");
            inputNama.requestFocus();
        } else if (Jenis.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Jenis produk tidak boleh kosong");
            inputJenis2.requestFocus();
        } else if (Harga.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Harga produk tidak boleh kosong");
            inputHarga.requestFocus();
        } else if (Stok.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Stok produk tidak boleh kosong");
            inputStok.requestFocus();
        }
        
        else if (!(new Scanner(Harga).hasNextInt())) {
            JOptionPane.showMessageDialog(null,"Harga produk harus angka");
            inputHarga.requestFocus();
        } else if (!(new Scanner(Stok).hasNextInt())) {
            JOptionPane.showMessageDialog(null,"Stok produk harus angka");
            inputStok.requestFocus();
        } else{
        try {
            // TODO add your handling code here:
            Connection cn = (Connection)Conn.koneksiDB();
            cn.createStatement().executeUpdate("insert into gbarang(KodeBarang,NamaBarang,Jenis,Harga,Stok)"+
                    "VALUES('"+KodeBarang+"','"+NamaBarang+"','"+Jenis+"','"+Harga+"','"+Stok+"')");
        tampilkanData();
            Clear();
            SettOff();
            JOptionPane.showMessageDialog(null, "Data Behasil Ditambahkan..!!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong..!!");
        }   catch (ClassNotFoundException ex) {
                Logger.getLogger(GBarang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tSimpanActionPerformed

    private void tKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKembaliActionPerformed
        // TODO add your handling code here:
        Clear();
        tSimpan.setEnabled(false);
        tEdit.setEnabled(false);
        tHapus.setEnabled(false);
        SettOff();
    }//GEN-LAST:event_tKembaliActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputHarga;
    private javax.swing.JTextField inputID;
    private javax.swing.JComboBox<String> inputJenis2;
    private javax.swing.JTextField inputKode;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputStok;
    private javax.swing.JLabel jHSatuan;
    private javax.swing.JLabel jJBarang;
    private javax.swing.JLabel jKBarang;
    private javax.swing.JLabel jKBarang1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jNBarang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jSGudang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tEdit;
    private javax.swing.JButton tHapus;
    private javax.swing.JButton tKeluar;
    private javax.swing.JButton tKembali;
    private javax.swing.JButton tSimpan;
    private javax.swing.JButton tTambah;
    private javax.swing.JTable tabelBarang;
    // End of variables declaration//GEN-END:variables
}
